import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { SOUNDS, LOOPS } from "../lib/sound-map.mjs";

// assets/sfx/*.wav are generated by tools/gen_sounds.py: every name in SOUNDS
// must exist as a 22 050 Hz mono 16-bit WAV, the loops must start and end on
// a zero so SoundEffect repeats them without a seam, and the generator must
// reproduce the committed bytes exactly, so an edited piece without a
// regenerated file fails here. The regeneration needs numpy; without it that
// one test skips with a note and the header checks still run.

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SFX = join(ROOT, "assets", "sfx");
const TOOL = join(ROOT, "tools", "gen_sounds.py");

const RATE = 22050;
/** How close to zero (in 16-bit units) a loop's first and last samples must be. */
const ZERO_TOLERANCE = 64;

/** Expected lengths in seconds (the plan's table); one-shots may drift a little, loops not at all. */
const SECONDS = {
  start: 4.0, "waka-a": 0.07, "waka-b": 0.07,
  "siren-1": 0.5, "siren-2": 0.5, "siren-3": 0.5, "siren-4": 0.5, "siren-5": 0.42,
  fright: 0.3, eyes: 0.25,
  "ghost-eaten": 0.45, death: 1.6, "extra-life": 0.6, "level-clear": 1.2, fruit: 0.3,
};

const hasNumpy = spawnSync("python3", ["-c", "import numpy"], { encoding: "utf8" }).status === 0;

function wavPath(name) {
  return join(SFX, name + ".wav");
}

/** The RIFF/WAVE header and the PCM samples of a 16-bit mono file. */
function parseWav(buf) {
  assert.equal(buf.toString("latin1", 0, 4), "RIFF");
  assert.equal(buf.toString("latin1", 8, 12), "WAVE");
  let offset = 12;
  let format = null;
  let data = null;
  while (offset + 8 <= buf.length) {
    const id = buf.toString("latin1", offset, offset + 4);
    const size = buf.readUInt32LE(offset + 4);
    const body = buf.subarray(offset + 8, offset + 8 + size);
    if (id === "fmt ") {
      format = {
        audioFormat: body.readUInt16LE(0),
        channels: body.readUInt16LE(2),
        rate: body.readUInt32LE(4),
        bits: body.readUInt16LE(14),
      };
    } else if (id === "data") {
      data = body;
    }
    offset += 8 + size + (size % 2);
  }
  assert.ok(format, "fmt chunk");
  assert.ok(data, "data chunk");
  const samples = new Int16Array(data.buffer, data.byteOffset, data.length / 2);
  return { format, samples };
}

function sha256(buf) {
  return createHash("sha256").update(buf).digest("hex");
}

test("every sound in SOUNDS exists under assets/sfx and nothing else does", () => {
  for (const name of SOUNDS) assert.ok(existsSync(wavPath(name)), name + ".wav");
  assert.ok(!existsSync(join(SFX, ".gitkeep")), "the placeholder is gone");
});

test("each file is a 22050 Hz mono 16-bit PCM WAV of the planned length", () => {
  for (const name of SOUNDS) {
    const { format, samples } = parseWav(readFileSync(wavPath(name)));
    assert.deepEqual(format, { audioFormat: 1, channels: 1, rate: RATE, bits: 16 }, name);
    const seconds = samples.length / RATE;
    const tolerance = LOOPS.includes(name) ? 0.001 : 0.05 * SECONDS[name];
    assert.ok(Math.abs(seconds - SECONDS[name]) <= tolerance, `${name}: ${seconds.toFixed(3)} s, expected ${SECONDS[name]} s`);
  }
});

test("loops start and end on a zero so they repeat without a seam", () => {
  for (const name of LOOPS) {
    const { samples } = parseWav(readFileSync(wavPath(name)));
    assert.ok(Math.abs(samples[0]) <= ZERO_TOLERANCE, `${name} starts at ${samples[0]}`);
    assert.ok(Math.abs(samples[samples.length - 1]) <= ZERO_TOLERANCE, `${name} ends at ${samples[samples.length - 1]}`);
  }
});

test("every file peaks near -3 dBFS (eyes at -9) and is not silent", () => {
  for (const name of SOUNDS) {
    const { samples } = parseWav(readFileSync(wavPath(name)));
    let peak = 0;
    for (const s of samples) peak = Math.max(peak, Math.abs(s));
    const expected = name === "eyes" ? 32767 * 10 ** (-9 / 20) : 32767 * 10 ** (-3 / 20);
    assert.ok(Math.abs(peak - expected) <= 2, `${name} peaks at ${peak}, expected ~${Math.round(expected)}`);
  }
});

test("tools/gen_sounds.py regenerates assets/sfx byte for byte", { skip: hasNumpy ? false : "python3 cannot import numpy" }, () => {
  const dir = mkdtempSync(join(tmpdir(), "pacman-sfx-"));
  try {
    const result = spawnSync("python3", [TOOL, "--out", dir], { encoding: "utf8" });
    assert.equal(result.status, 0, result.stderr);
    for (const name of SOUNDS) {
      const fresh = readFileSync(join(dir, name + ".wav"));
      const committed = readFileSync(wavPath(name));
      assert.equal(sha256(fresh), sha256(committed), `${name}.wav drifted from the generator (run python3 tools/gen_sounds.py)`);
    }
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
