import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// assets/icon.png is generated by tools/gen-icon.py: it must be a 256x256 RGBA
// PNG and the generator must reproduce it byte for byte, so an edited grid
// without a regenerated file fails here.

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ICON = join(ROOT, "assets", "icon.png");
const TOOL = join(ROOT, "tools", "gen-icon.py");

const SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

function ihdr(png) {
  assert.deepEqual(png.subarray(0, 8), SIGNATURE, "PNG signature");
  assert.equal(png.readUInt32BE(8), 13, "IHDR length");
  assert.equal(png.toString("latin1", 12, 16), "IHDR");
  return {
    width: png.readUInt32BE(16),
    height: png.readUInt32BE(20),
    depth: png[24],
    colourType: png[25],
    interlace: png[28],
  };
}

test("assets/icon.png is a 256x256 8-bit RGBA PNG", () => {
  const png = readFileSync(ICON);
  const header = ihdr(png);
  assert.equal(header.width, 256);
  assert.equal(header.height, 256);
  assert.equal(header.depth, 8);
  assert.equal(header.colourType, 6, "RGBA");
  assert.equal(header.interlace, 0);
  assert.equal(png.toString("latin1", png.length - 8, png.length - 4), "IEND");
});

test("tools/gen-icon.py regenerates assets/icon.png byte for byte", () => {
  const dir = mkdtempSync(join(tmpdir(), "pacman-icon-"));
  try {
    const out = join(dir, "icon.png");
    const result = spawnSync("python3", [TOOL, out], { encoding: "utf8" });
    assert.equal(result.status, 0, result.stderr);
    assert.deepEqual(readFileSync(out), readFileSync(ICON), "committed icon matches the generator");
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
