// Generated by tools/gen-attract.mjs; do not edit. Rerun it when the maze
// or the game rules change (tests/attract.test.mjs says when).
//
// checksum 127980185 (FNV-1a of the maze text), seed 11,
// 2400 ticks, score 1860 at tick 2400 (playing).

export const ATTRACT = Object.freeze({
  checksum: 127980185,
  seed: 11,
  length: 2400,
  expectedScore: 1860,
  expectedTick: 2400,
  expectedPhase: "playing",
  runs: [
    ["left",124], ["up",23], ["left",23], ["up",14], ["down",10], ["left",31], ["down",23], ["left",14],
    ["down",23], ["left",14], ["down",23], ["right",37], ["up",45], ["down",16], ["left",12], ["right",32],
    ["up",21], ["right",42], ["up",21], ["left",13], ["right",32], ["up",13], ["down",9], ["right",28],
    ["down",22], ["left",5], ["down",50], ["left",130], ["up",20], ["right",100], ["up",23], ["left",14],
    ["right",10], ["down",20], ["right",48], ["up",23], ["left",5], ["right",18], ["up",23], ["left",98],
    ["right",132], ["up",20], ["right",69], ["left",2], ["up",164], ["left",32], ["down",23], ["left",5],
    ["down",50], ["up",18], ["left",76], ["up",23], ["left",5], ["up",23], ["left",32], ["down",90],
    ["left",124], ["up",20], ["left",20], ["up",126], ["left",39], ["up",23], ["left",22], ["down",10],
  ],
});
