#!/usr/bin/env node
// Generate lib/attract-script.mjs: the inputs for the attract demo.
//
// An autopilot plays level 1 from a fixed seed with the ghosts on: at every
// tile it heads for the nearest remaining pellet by BFS (the same pilot the
// game tests use), blind to the ghosts, so it dies the way a demo should.
// The per-tick directions are run-length encoded together with the maze
// checksum, the final score and the tick it was reached, and written as an
// ES module both QML and `node --test` read. Rerun whenever the maze or the
// rules change:
//
//   node tools/gen-attract.mjs
//
// tests/attract.test.mjs regenerates in memory and fails if the committed
// script differs.

import { writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, resolve } from "node:path";
import { LEVEL_1 } from "../lib/maze-data.mjs";
import { parseMaze, tileAt, isWalkable, TILE } from "../lib/maze.mjs";
import { DIRS } from "../lib/input.mjs";
import { tileOf } from "../lib/player.mjs";
import { createState, step, TICK } from "../lib/game.mjs";
import { mazeChecksum } from "../lib/attract.mjs";

export const ATTRACT_SEED = 11;
/** The demo never runs longer than this (40 s), game over or not. */
export const ATTRACT_MAX_TICKS = 2400;

/** Neighbours of a tile over walkable tiles, with tunnel wrap. */
function neighbours(board, tile) {
  const out = [];
  for (const name of Object.keys(DIRS)) {
    const d = DIRS[name];
    const nx = ((tile.x + d.dx) % board.width + board.width) % board.width;
    const ny = tile.y + d.dy;
    if (ny < 0 || ny >= board.height || !isWalkable(tileAt(board, nx, ny))) continue;
    out.push({ x: nx, y: ny, dir: name });
  }
  return out;
}

/** BFS from `from`: the nearest remaining pellet and the first step's direction towards `to`. */
function bfs(board, from, to) {
  const key = t => t.y * board.width + t.x;
  const firstDir = new Map([[key(from), null]]);
  const queue = [from];
  let nearest = null;
  while (queue.length) {
    const cur = queue.shift();
    const kind = tileAt(board, cur.x, cur.y);
    if (nearest === null && (kind === TILE.PELLET || kind === TILE.POWER)) nearest = cur;
    if (to && cur.x === to.x && cur.y === to.y) return { nearest, dir: firstDir.get(key(cur)) };
    for (const n of neighbours(board, cur)) {
      const k = key(n);
      if (firstDir.has(k)) continue;
      firstDir.set(k, firstDir.get(key(cur)) ?? n.dir);
      queue.push(n);
    }
  }
  return { nearest, dir: null };
}

/** Run-length encode a list of directions into [[dir, ticks], ...]. */
export function encodeRuns(dirs) {
  const runs = [];
  for (const dir of dirs) {
    const last = runs[runs.length - 1];
    if (last && last[0] === dir) last[1]++;
    else runs.push([dir, 1]);
  }
  return runs;
}

/**
 * Play the autopilot from `mazeText` and return the script object:
 * { checksum, seed, length, expectedScore, expectedTick, runs }.
 */
export function generateAttract(mazeText = LEVEL_1, opts = {}) {
  const seed = opts.seed ?? ATTRACT_SEED;
  const maxTicks = opts.maxTicks ?? ATTRACT_MAX_TICKS;
  const maze = parseMaze(mazeText);
  let s = createState(maze, { seed });
  const dirs = [];
  let target = null;
  while (s.tick < maxTicks && s.phase !== "game-over") {
    const tile = tileOf(s.player, s.board);
    if (!target || tileAt(s.board, target.x, target.y) === TILE.EMPTY) target = bfs(s.board, tile).nearest;
    const want = target ? bfs(s.board, tile, target).dir : null;
    dirs.push(want);
    s = step(s, { wantDir: want }, TICK).state;
  }
  return {
    checksum: mazeChecksum(mazeText),
    seed,
    length: dirs.length,
    expectedScore: s.score,
    expectedTick: s.tick,
    expectedPhase: s.phase,
    runs: encodeRuns(dirs),
  };
}

/** The module text for a script, runs packed eight to a line. */
export function formatScript(script) {
  const lines = [];
  for (let i = 0; i < script.runs.length; i += 8) {
    lines.push("    " + script.runs.slice(i, i + 8).map(r => JSON.stringify(r)).join(", ") + ",");
  }
  return [
    "// Generated by tools/gen-attract.mjs; do not edit. Rerun it when the maze",
    "// or the game rules change (tests/attract.test.mjs says when).",
    "//",
    `// checksum ${script.checksum} (FNV-1a of the maze text), seed ${script.seed},`,
    `// ${script.length} ticks, score ${script.expectedScore} at tick ${script.expectedTick} (${script.expectedPhase}).`,
    "",
    "export const ATTRACT = Object.freeze({",
    `  checksum: ${script.checksum},`,
    `  seed: ${script.seed},`,
    `  length: ${script.length},`,
    `  expectedScore: ${script.expectedScore},`,
    `  expectedTick: ${script.expectedTick},`,
    `  expectedPhase: ${JSON.stringify(script.expectedPhase)},`,
    "  runs: [",
    ...lines,
    "  ],",
    "});",
    "",
  ].join("\n");
}

export const SCRIPT_PATH = resolve(dirname(fileURLToPath(import.meta.url)), "../lib/attract-script.mjs");

function main() {
  const script = generateAttract();
  writeFileSync(SCRIPT_PATH, formatScript(script));
  console.log(`wrote ${SCRIPT_PATH}`);
  console.log(`checksum ${script.checksum} seed ${script.seed} length ${script.length} runs ${script.runs.length}`);
  console.log(`expectedScore ${script.expectedScore} expectedTick ${script.expectedTick} (${script.expectedPhase})`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) main();
